# Generated by Django 4.2.1 on 2023-05-13 13:42

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utulisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number_code', models.CharField(choices=[('+93', '+93'), ('+355', '+355'), ('+213', '+213'), ('+1684', '+1684'), ('+376', '+376'), ('+244', '+244'), ('+1264', '+1264'), ('+672', '+672'), ('+1268', '+1268'), ('+54', '+54'), ('+374', '+374'), ('+297', '+297'), ('+61', '+61'), ('+43', '+43'), ('+994', '+994'), ('+1242', '+1242'), ('+973', '+973'), ('+880', '+880'), ('+1246', '+1246'), ('+375', '+375'), ('+32', '+32'), ('+501', '+501'), ('+229', '+229'), ('+1441', '+1441'), ('+975', '+975'), ('+591', '+591'), ('+387', '+387'), ('+267', '+267'), ('+47', '+47'), ('+55', '+55'), ('+246', '+246'), ('+1284', '+1284'), ('+673', '+673'), ('+359', '+359'), ('+226', '+226'), ('+257', '+257'), ('+855', '+855'), ('+237', '+237'), ('+1', '+1'), ('+238', '+238'), ('011-599-', '011-599-'), ('+ 345', '+ 345'), ('+236', '+236'), ('+235', '+235'), ('+56', '+56'), ('+86', '+86'), ('+61', '+61'), ('+61', '+61'), ('+57', '+57'), ('+269', '+269'), ('+682', '+682'), ('+506', '+506'), ('+385', '+385'), ('+53', '+53'), ('+599', '+599'), ('+357', '+357'), ('+420', '+420'), ('+243', '+243'), ('+45', '+45'), ('+253', '+253'), ('+1767', '+1767'), ('+1849', '+1849'), ('+593', '+593'), ('+20', '+20'), ('+503', '+503'), ('+240', '+240'), ('+291', '+291'), ('+372', '+372'), ('+268', '+268'), ('+251', '+251'), ('+500', '+500'), ('+298', '+298'), ('+679', '+679'), ('+358', '+358'), ('+33', '+33'), ('+594', '+594'), ('+689', '+689'), ('00+33+', '00+33+'), ('+241', '+241'), ('+220', '+220'), ('+995', '+995'), ('+49', '+49'), ('+233', '+233'), ('+350', '+350'), ('+30', '+30'), ('+299', '+299'), ('+1473', '+1473'), ('+590', '+590'), ('+1671', '+1671'), ('+502', '+502'), ('+44', '+44'), ('+224', '+224'), ('+245', '+245'), ('+595', '+595'), ('+509', '+509'), ('+672', '+672'), ('+504', '+504'), ('+852', '+852'), ('+36', '+36'), ('+354', '+354'), ('+91', '+91'), ('+62', '+62'), ('+355', '+355'), ('+964', '+964'), ('+353', '+353'), ('+44', '+44'), ('+972', '+972'), ('+39', '+39'), ('+225', '+225'), ('+1876', '+1876'), ('+81', '+81'), ('+44', '+44'), ('+962', '+962'), ('+77', '+77'), ('+254', '+254'), ('+686', '+686'), ('+383', '+383'), ('+965', '+965'), ('+996', '+996'), ('+856', '+856'), ('+371', '+371'), ('+961', '+961'), ('+266', '+266'), ('+231', '+231'), ('+218', '+218'), ('+423', '+423'), ('+370', '+370'), ('+352', '+352'), ('+853', '+853'), ('+261', '+261'), ('+265', '+265'), ('+60', '+60'), ('+960', '+960'), ('+223', '+223'), ('+356', '+356'), ('+692', '+692'), ('+596', '+596'), ('+222', '+222'), ('+230', '+230'), ('+262', '+262'), ('+52', '+52'), ('+691', '+691'), ('+373', '+373'), ('+377', '+377'), ('+976', '+976'), ('+382', '+382'), ('+1664', '+1664'), ('+212', '+212'), ('+258', '+258'), ('+95', '+95'), ('+264', '+264'), ('+674', '+674'), ('+977', '+977'), ('+31', '+31'), ('+687', '+687'), ('+64', '+64'), ('+505', '+505'), ('+227', '+227'), ('+234', '+234'), ('+683', '+683'), ('+672', '+672'), ('+850', '+850'), ('+389', '+389'), ('+1670', '+1670'), ('+47', '+47'), ('+968', '+968'), ('+92', '+92'), ('+680', '+680'), ('+970', '+970'), ('+507', '+507'), ('+675', '+675'), ('+595', '+595'), ('+51', '+51'), ('+63', '+63'), ('+64', '+64'), ('+48', '+48'), ('+351', '+351'), ('+1939', '+1939'), ('+974', '+974'), ('+242', '+242'), ('+40', '+40'), ('+7', '+7'), ('+250', '+250'), ('++262', '++262'), ('+590', '+590'), ('+290', '+290'), ('+1869', '+1869'), ('+1758', '+1758'), ('+590', '+590'), ('+508', '+508'), ('+1784', '+1784'), ('+685', '+685'), ('+378', '+378'), ('+966', '+966'), ('+221', '+221'), ('+381', '+381'), ('+248', '+248'), ('+232', '+232'), ('+65', '+65'), ('1-721', '1-721'), ('+421', '+421'), ('+386', '+386'), ('+677', '+677'), ('+252', '+252'), ('+27', '+27'), ('+500', '+500'), ('+82', '+82'), ('+211', '+211'), ('+34', '+34'), ('+94', '+94'), ('+249', '+249'), ('+597', '+597'), ('+47', '+47'), ('+46', '+46'), ('+41', '+41'), ('+963', '+963'), ('+239', '+239'), ('+886', '+886'), ('+992', '+992'), ('+255', '+255'), ('+66', '+66'), ('+670', '+670'), ('+228', '+228'), ('+690', '+690'), ('+676', '+676'), ('+1868', '+1868'), ('+216', '+216'), ('+90', '+90'), ('+993', '+993'), ('+1649', '+1649'), ('+688', '+688'), ('+256', '+256'), ('+380', '+380'), ('+971', '+971'), ('+44', '+44'), ('+1', '+1'), ('-1-10', '-1-10'), ('+1340', '+1340'), ('+598', '+598'), ('+998', '+998'), ('+678', '+678'), ('+1340', '+1340'), ('+58', '+58'), ('+84', '+84'), ('+681', '+681'), ('+212', '+212'), ('+967', '+967'), ('+260', '+260'), ('+263', '+263'), ('+358', '+358')], max_length=8)),
                ('phone_number', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
